main: me.koenn.LTPT.LTPTowny
name: LTPTowny
version: 1.8-ALPHA
author: Koenn

commands:
  towny:
    usage: /towny <subcommand>
    description: General towny command;
  town:
    usage: /town <subcommand>
    description: General towny command;
  t:
    usage: /t<subcommand>
    description: General towny command;